{
 "title": "Augusta Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "System Performance metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Workers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(scheduler_active_workers)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Global Error rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_result_tasks_total{status=\"ERROR\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scheduler_result_tasks_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50 Task Round-Trip Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(scheduler_task_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Task Round-Trip Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(scheduler_task_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Task Round-Trip Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(scheduler_task_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate per worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (worker_id) (scheduler_result_tasks_total{status=\"ERROR\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (worker_id) (rate(scheduler_result_tasks_total{status=\"ERROR\"}[$__rate_interval])) \r\n  / \r\nsum by (worker_id) (rate(scheduler_result_tasks_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50 Percentile Workload",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, worker_id) (rate(scheduler_task_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90 Percentile Workload",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, worker_id) (rate(scheduler_task_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 Percentile Workload",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, worker_id) (rate(scheduler_task_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50 Percentile Processing Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, worker_id) (rate(scheduler_task_scheduling_lag_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90 Percentile Processing Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, worker_id) (rate(scheduler_task_scheduling_lag_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99 Percentile Processing Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, worker_id) (rate(scheduler_task_scheduling_lag_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Scheduler Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"augusta-scheduler\"} |= ``"
    }
   ]
  },
  {
   "title": "Worker Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"augusta-worker\"} |= ``"
    }
   ]
  },
  { "title": "System traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Dispatch Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "filters": [
      {
       "id": "391c0d76",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "augusta-scheduler" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "dispatcher.run" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"augusta-scheduler\" && name=\"dispatcher.run\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Dispatch reaper traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "filters": [
      {
       "id": "391c0d76",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "augusta-scheduler" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "dispatcher.reaper" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"augusta-scheduler\" && name=\"dispatcher.run\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}